### ISSUE TITLE
Review from Kostiantyn.S

### ISSUE THREAD

**Issue by DelDmc** [iva-stasia/js-questions#2]
Generally speaking the code is clean, laconic, you keep it simple and well-readable
There was a good decision to move questions dataset to separate file >>> [commit 1f65c1d](https://github.com/iva-stasia/js-questions/commit/1f65c1d81d0571a799d08a5fc5a2955b95bacf65)

There was a good decision to use method `push` instead of `unshift` >>> [commit d80b2af](https://github.com/iva-stasia/js-questions/commit/d80b2af17dc615a713cf37c1382f958919558379)

However, the only one minor remark in regards of function `addQuestion()` I would leave here
https://github.com/iva-stasia/js-questions/blob/d80b2af17dc615a713cf37c1382f958919558379/main.js#L81

In your code this function is doing two actions:
1. Adding a new question to dataset array, 
2. Looping through the questions to display updated data
I would suggest separate logic for updating dataset array, i.e. make one separate function to update dataset
- As instance, `addQuestionToDataset(dataset, questionText)`

```
function addQuestionToDataset(dataset, questionText){
    dataset.push({
        text: questionText,
        isLearned: false,
    });
}
```

- As instance, `function renderNewQuestion()`
```
function renderNewQuestion() {
    const addQuestionField = document.querySelector('#addQuestionField');
    addQuestionToDataset(questions, addQuestionField.value);

    updateCards();
    addQuestionField.value = '';
}
```
Dividing  one function which performs few actions to smaller functions will lead to increase of lines of code. Nevertheless it will make the code more maintainable and easier for debugging

Good job, Anastasiia!

**Comment by iva-stasia** [comment]
Thanks for the review!
I completely agree with the comments.
Please check the [рull request](https://github.com/iva-stasia/js-questions/pull/3).
